export const channels = {
  bootstrap: "uruvam:bootstrap",
  credentialStore: "uruvam:credential-store",
  credentialStatus: "uruvam:credential-status",
  projectsList: "uruvam:projects-list",
  projectCreate: "uruvam:project-create",
  projectReveal: "uruvam:project-reveal",
  projectEditor: "uruvam:project-editor",
  projectSnapshot: "uruvam:project-snapshot",
  referenceImport: "uruvam:reference-import",
  modelsList: "uruvam:models-list",
  generate: "uruvam:generate",
  stop: "uruvam:stop",
  previewOpen: "uruvam:preview-open",
  previewBounds: "uruvam:preview-bounds",
  previewHide: "uruvam:preview-hide",
  commentCreate: "uruvam:comment-create",
  commentResolve: "uruvam:comment-resolve",
  directionAction: "uruvam:direction-action",
  extensionTrust: "uruvam:extension-trust",
  extensionList: "uruvam:extension-list",
  event: "uruvam:event",
} as const;
